# Generated by Django 5.0.3 on 2024-04-15 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Babe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('gender', models.CharField(blank=True, max_length=2, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('sponser', models.CharField(blank=True, max_length=100, null=True)),
                ('time_in', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_out', models.DateTimeField(auto_now_add=True, null=True)),
                ('c_stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='keshoApp.category_stay')),
            ],
        ),
    ]
