# Generated by Django 5.0.3 on 2024-04-16 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keshoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('payno', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, default='Ugx', max_length=10, null=True)),
                ('c_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='keshoApp.category_stay')),
            ],
        ),
        migrations.AddField(
            model_name='babe',
            name='c_fee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='keshoApp.payment'),
        ),
    ]
