# Generated by Django 5.0.3 on 2024-04-19 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keshoApp', '0003_alter_babe_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babe',
            name='c_fee',
        ),
        migrations.AddField(
            model_name='payment',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='keshoApp.babe'),
        ),
    ]
